sudo: required
services:
  - docker

before_install:
  - docker build -t rnagarajago/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run rnagarajago/react-test npm test -- --coverage

after_success: 
  - docker build -t rnagarajago/multi-client ./client
  - docker build -t rnagarajago/multi-nginx ./nginx
  - docker build -t rnagarajago/multi-server ./server
  - docker build -t rnagarajago/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push rnagarajago/multi-client
  - docker push rnagarajago/multi-nginx
  - docker push rnagarajago/multi-server
  - docker push rnagarajago/multi-worker

  